config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount Notifications::Engine => '/notifications'
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :categories
  resources :posts do
    resources :comments
    resources :likes
  end
  resources :userlists
  post 'friend_request' => 'friendships#request_friend'
  post 'accept_friend' => 'friendships#accept_request'
  delete 'decline_request' => 'friendships#decline_request'
  delete 'unfriend' => 'friendships#unfriend'
  put 'block_friend' => 'friendships#block'
  get 'view_previous_comments' => 'comments#view_previous_comments'
  resources :notifications
  resources :search_users, only: [:index]
  root to: 'userlists#index'
end

app/controllers/userlists_controller.rb
# frozen_string_literal: true

class UserlistsController < ApplicationController #:nodoc:
  def index
    friend_suggestion
    @post = Post.new
    friends_posts
    current_user_notifications
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    @post = Post.new
  end

  private

  def friend_suggestion
    @users = User.where.not(id: current_user.id)
  end

  def friends_posts
    @posts = current_user.friends.map(&:posts).push(current_user.posts).flatten
  end

  def current_user_notifications
    @notifications =
      Notification.where(user_id: current_user).order('created_at DESC')
  end
end

app/views/userlists/_postcreate.html.erb
<div class="container">
  <div class="row" id = "postform">
    <div class="col-sm-5 col-sm-offset-3">
      <h1 id="post" class="text-center"><b>Create New Post</b></h1>
      <%= bootstrap_form_for(@post) do |f| %>
        <%= f.text_field :title, maxlenght: 150, placeholder: 'Title', class: 'form-controls' %>
        <%= f.file_field :postphotos %>
        <%= f.text_area :content, rows: 6 %>
        <%= f.collection_select :category_id, Category.all, :id, :name, class: 'form-controls'%> 
        <%= f.submit "Create", id: 'postbutton', class: 'form-controls btn btn-primary', remote: true %>
        <%= link_to "Create Category" , new_category_path, class: 'btn btn-primary'%>
      <% end %>
    </div>
  </div> 
</div>

app/views/userlists/index.html.erb
<body>
  <%= render 'postcreate' %>
  <div class="row", id= "user">
    <% @users.each do |user| %>
      <% if current_user.blocked_friend_ids.exclude?(user.id) %>	 
        <div class="col-sm-3">
          <div class="card">
            <%= image_tag user.avatar.url(:medium), :size => "380x240" %>
            <div class="card-body">
              <h3 class="card text"><%=user.name %></h3>
              <p class="card-text"><%=user.email %></p>
              <%= link_to "See Profile", userlist_path(user.id)%>
              <% if current_user.friends_with?(user) %>
                <%= link_to "Unfriend", unfriend_path(user_id: user.id), method: :delete%>
              <% elsif current_user.pending_friend_ids.include?(user.id) %>
                <%= link_to "Request Sent" %>
              <% else %>
                <%= link_to "Send Request", friend_request_path(user_id: user.id), method: :post%>
              <% end%> 
            </div>
          </div>
        </div>
      <%end%>
    <%end %>
  </div> 
  
  <% @posts.each do |post| %>
    <div class= "posts">
      <div id= "ajax-posts", class="col-sm-4 col-sm-offset-4">
        <p><%= image_tag post.user.avatar.url(:medium), :class=> "img-circular" %>
          &nbsp;<strong id = "posted_by"><%= link_to post.user.name,userlist_path(post.user.id)%></br><%= time_ago_in_words(post.created_at) %> ago</strong>
          <%= link_to(image_tag("delete.png", class: 'image-responsive',:size => "35x35"), post_path(post.id),  method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "delete_post") %>
        </p>

        <div class="card">
          <div class="card-body">
            <h3 class="card text"><%=post.title %></h3>
              <strong >
                <%= post.likes.count %>
                <% liked = post.likes.find { |like| like.user_id == current_user.id} %>
             
                <% if liked %>
                  <%= link_to "Unlike", post_like_path(liked.post_id, liked.id), method: :delete %>
                <% else %>
                  <%= link_to  (post.likes.count)<= 1 ? "Like": "Likes", post_likes_path(post.id), method: :post %>
              <% end %>
              </strong>

              <% if post.postphotos.present? %>
                <%= image_tag post.postphotos.url(:medium), :size => "300x200" %>
              <% end %>
              <p class="card-text"><%=post.content %></p>
              <b>Comments:</b><br>
              <%= render partial: 'layouts/comment', locals: {comments: post.comments.last(5), post: post}%>
              <%= form_with scope: :comment, url: post_comments_path(post.id),:id => 'reset-form',:remote => true, method: :post do |f|%>
                <%= f.text_field :body %>
                <%= f.submit %>
              <% end %>
            </div>
          </div>
        </br></br>
     </div>
    </div> 
  <%end%>
</body>

app/views/userlists/show.html.erb
<div class="row">
	<div class="col-sm-2", id = "profile_image">
		<%= image_tag @user.avatar.url(:medium), :size => "300x200" %>
		<p class="card text", id = "profile_info"><%=@user.name %><br/>
			<%=@user.email %>
			<% if @user.id != current_user.id %>
				<%= link_to "Block Friend", block_friend_path(user_id: @user.id), method: :put %>
			<% end %>
		</p>
	</div>
	<%= render 'postcreate'%>
</div>

<div class= "row">
	<div class="col-sm-6 col-sm-offset-3">
		<% @posts.each do |post| %> 
	  	<div class= "posts">
	    	<div class="col-sm-5 col-sm-offset-3">
	      	<p><%= image_tag post.user.avatar.url(:medium), :class=> "img-circular" %>
	        &nbsp;<strong id = "posted_by"><%= link_to post.user.name,userlist_path(post.user.id)%></br><%= time_ago_in_words(post.created_at) %> ago
	        </strong>
	      	</p>
	      	<div class="card">
	        	<div class="card-body">
	          	<h3 class="card text"><%=post.title %></h3>
	            <%= post.likes.count %>
	            <% liked = post.likes.find { |like| like.user_id == current_user.id} %>

	         		<% if liked %>
	              <%= link_to "Unlike", post_like_path(liked.post_id, liked.id), method: :delete %>
	            <% else %>
	              <%= link_to  (post.likes.count)<= 1 ? "Like": "Likes", post_likes_path(post.id), method: :post %>
	            <% end %>

	            <% if post.postphotos.present? %>
	              <%= image_tag post.postphotos.url(:medium), :size => "300x200" %>
	            <% end %>
	            <p class="card-text"><%=post.content %></p>
	              
	            <b>Comments:</b>
	            <%= render partial: 'layouts/comment', locals: {comments: post.comments.last(5), post: post}%>
	           	<%= form_with scope: :comment, url: post_comments_path(post.id),:id => 'reset-form',:remote => true, method: :post do |f|%>
	           		<%= f.text_field :body %>
	           		<%= f.submit %>
	           	<% end %>
	          </div>
	        </div>
	      </div>
	    </div>
	  <%end%>
	</div>
</div>