config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount Notifications::Engine => '/notifications'
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :categories
  resources :posts do
    resources :comments
    resources :likes
  end
  resources :userlists
  post 'friend_request' => 'friendships#request_friend'
  post 'accept_friend' => 'friendships#accept_request'
  delete 'decline_request' => 'friendships#decline_request'
  delete 'unfriend' => 'friendships#unfriend'
  put 'block_friend' => 'friendships#block'
  get 'view_previous_comments' => 'comments#view_previous_comments'
  resources :notifications
  resources :search_users, only: [:index]
  root to: 'userlists#index'
end

app/views/layouts/_comment.html.erb
<div id = "create-comment-<%= post.id %>">
	<% comments.each_with_index do |comment, i|%>
		<p class="card-text">
			<%= image_tag comment.user.avatar.url(:medium), :size => "20x18" %>&nbsp;&nbsp;<%= comment.body%>
			<strong> <%= time_ago_in_words(comment.created_at) %> ago </strong>
			<%= link_to(image_tag("garbage.png", class: 'image-responsive',:size => "20x20"), post_comment_path(comment.post_id, comment.id),  method: :delete, data: { confirm: 'Are you sure?'},remote: true, class: "delete_comment") %>
		</p>
		<% @offset = i+6%>
	<% end %>
	<% total_count = post.comments.count%>
	<% if total_count > 5	&& total_count != @offset-5%>
		<%= link_to 'View Previous', view_previous_comments_path(post_id: post.id, offset: @offset),remote: true, id: "view-previous" %>
	<%end%>
	<% if post.comments.blank? %>
		<i>Be the first one to comment</i>
	<%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse", id="nav-fixed">
  <%= link_to 'FriendBook',root_path, class: 'navbar-brand' %>
  <% if user_signed_in? %>
    <%= form_tag search_users_path, method: 'get' do%>
        <%= text_field_tag :search_user,params[:search] %>
        <%= submit_tag "Search", class: 'form-controls btn btn-primary' %>
    <% end %>
  
      <ul class="nav navbar-nav">
        <li class="dropdown">
        <ul class="nav-item dropdown ">
          <button id="nav-toggle", class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
            <%= image_tag current_user.avatar.url(:thumb), :class=> "profile_image"%>
            <strong><%= current_user.name %></strong></button>
          <span class="caret"></span>
          <ul class= "dropdown-menu", id="dropdown-style" >
            <div>
            <li>
              <%= link_to 'Edit Profile', edit_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
            </li>
            <li><%= link_to 'View Profile', userlist_path(current_user.id) %></li>
          </div>
          </ul>
        </ul>
        </li>
      </ul>

      <ul class="nav-item dropdown ">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" id="notification"> 
          <%= image_tag("friend.png",:size => "30x30") %>
        
        <% request_count = current_user.requested_friends.count %>
          <% if request_count > 0 %>
           <span class="badge"><%= request_count %></span></button>
            <span class="caret"></span>
            <ul class= "dropdown-menu", id="dropdown-friend" >
              <% current_user.requested_friends.each do |friend| %>
                <div id="frienddiv",class="row" >
                  <li>
                   <div class="col-sm-7">
                      <%= image_tag friend.avatar.url(:thumb), :class=> "img-circular", :size => "20*20" %>
                      <strong><%= friend.name %> </strong>
                    </div> 

                    <div id="friendbutton" class="col-sm-5"> 
                      <%= link_to 'Accept', accept_friend_path(friend_id: friend.id),method: :post,class: "btn btn-primary"%>
                      <%= link_to 'Decline', decline_request_path(requested_id: friend.id),method: :delete, class: "btn btn-default"%>
                    </div>
                 </li>
                </div>
              <% end %>
          </ul>
          <% else %>
            <div>
              <ul class= "dropdown-menu", id="dropdown-style" >
                <p>No new requests</p>
            </div>
        <%end%>
     </ul>  

    <% if @notifications %>
     <ul class="nav-item dropdown ">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" id="notification"> 
          <%= image_tag("notify.png",:size => "30x30") %>
          <% notification_count = Notification.unread_count(current_user)%>
          <% if notification_count > 0 %>
            <span class="badge"><%= notification_count %></span></button>
            <span class="caret"></span>
          <%end%>
            <ul class= "dropdown-menu", id="notification_dropdown" >
              <div id="frienddiv",class="row" >
                <% @notifications.limit(10).each do |notification| %>
                  <% if notification.read_at %>
                    <div class="col-sm-12 read-notification">
                      <%= image_tag notification.actor.avatar.url(:thumb), :class=> "img-circular", :size => "10*10" %>
                      <%= link_to notification.actor.name, post_path(notification.second_target_id,
                          notification_id: notification.id)%> has commented on
                            <%= link_to notification.second_target.title %>
                    </div>
                  <% else %>
                    <div class="col-sm-12 unread-notification">
                      <%= image_tag notification.actor.avatar.url(:thumb), :class=> "img-circular", :size => "10*10" %>
                      <%= link_to notification.actor.name, post_path(notification.second_target_id,
                          notification_id: notification.id)%> has commented on
                      <%= link_to notification.second_target.title %>
                    </div>
                  <% end %>
                <% end %>
                <center><%= link_to 'See All', notifications_path%></center>
              </div>
          </ul>
      </ul>
    <% end %>

    <% else %>
      <ul class="nav navbar-nav navbar-right", id="login-nav">
        <li ><%= link_to 'Login', new_user_session_path, class: 'glyphicon glyphicon-user' %></li>
        <li ><%= link_to 'Signup', new_user_registration_path, class: 'glyphicon glyphicon-log-in' %></li>
      </ul>
    <% end %> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'toastr_rails/flash' %>

  <!--<% flash.each do |key, value| %>
    <div class="toast " data-autohide="false" style="position: fixed; top: 7rem; right: 1rem;">
    <div class="toast-header">
      <strong class="mr-auto text-primary">Notification</strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span>&times;</span>
      </button>
    </div>
    <div class="toast-body">
      <%= value %>
    </div>
  </div>
<% end %>-->
    
  <%= yield %>
  </body>
</html>